name: Release new version

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GOOS: js
      GOARCH: wasm
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
          cache: true
      - name: Build wasm
        run: |
          go build -o ./web/mykeys.wasm ./cmd/webassembly/main.go
      - name: Copy go wasm js engine
        run: |
          cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" ./web
      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with: 
          output: sha256_checksums.txt
          patterns: |
            web/mykeys.wasm
            web/wasm_exec.js
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        id: upload-release-asset
        with:
          files: |
            sha256_checksums.txt
            web/mykeys.wasm
            web/wasm_exec.js